apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  source:
    path: efk/kibana
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  project: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
