apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: home
  source:
    path: ha/overlay/prod
    repoURL: https://github.com/vicen404/gitops-argo.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
