apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
  labels:
    io.kompose.service: openai-client
  name: openai-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openai-client
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: openai-client
    spec:
      containers:
        - image: vicen404/openai-codex-client:3.4
          name: openai-client
          ports:
          - containerPort: 5173
            protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
