apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  labels:
    io.kompose.service: openai-server
  name: openai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openai-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: openai-server
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: secret-openai        
          image: vicen404/openai-codex-server:7.6
          name: openai-server
          ports:
          - containerPort: 5000
            protocol: TCP
      restartPolicy: Always
status: {}
