apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: openai-server
  name: openai-server
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: openai-server
status:
  loadBalancer: {}
