apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: openfaas-fn
spec: {}
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas
  namespace: argocd
spec:
  project: default
  source:
    chart: openfaas
    repoURL: https://openfaas.github.io/faas-netes/
    targetRevision: 10.0.19
    helm:
      releaseName: openfaas
      parameters:
      - name: functionNamespace
        value: openfaas-fn
      - name: generateBasicAuth
        value: "true"
      - name: ingress.enabled
        value: "true"
      - name: ingress.hosts[0].host
        value: gateway-openfaas-10-1-1-20.traefik.me
      - name: ingress.hosts[0].serviceName
        value: gateway
      - name: ingress.hosts[0].servicePort
        value: "8080"
      - name: ingress.hosts[0].path
        value: /
      - name: ingress.annotations.kubernetes.io/ingress.class
        value: nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openfaas
  project: openfaas
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
