apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- warp-demo-db-pvc.yaml
- warp-demo-db-deployment.yaml
- warp-demo-db-service.yaml
- warp-demo-wsgi-service.yaml
- warp-demo-wsgi-deployment.yaml
- warp-demo-nginx-cm.yaml
- warp-demo-nginx-deployment.yaml
- warp-demo-nginx-service.yaml
- warp-demo-ingress-wsgi.yaml

namespace: warp-prod
