apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-warp-db-claim
  namespace: warp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: portworx-shared-gp1
