apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: warp
data:
  default.conf: |
    server {
        server_name _;
        listen 80;
        location / {
            uwsgi_pass warp-demo-wsgi:8000;
            include uwsgi_params;
        }
    }

