apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: px-central
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: px-central
  source:
    path: pxb/pxb
    repoURL: https://github.com/vicen404/gitops-argo.git
    targetRevision: HEAD
  project: px-central
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
