commonLabels:
  app: argo-events-example

resources:
  - operate-workflow-sa.yaml
  - operate-workflow-role.yaml
  - operate-workflow-rolebinding.yaml
  - eventbus-default.yaml
  - event-source.yaml
  - sensor.yaml
  - ingress-argo-events.yaml

