apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-events/manifests/base
- github.com/argoproj/argo-events/manifests/name-space-install/rbac

namespace: argo-events
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --namespaced
    target:
      kind: Deployment
