apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 32560
        targetPort: 32560
  webhook:
    argo-events:
      port: "32560"
      endpoint: /argo-events
      method: POST
