apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
      - drop_event.when.regexp:
          or:
            kubernetes.pod.name: "kube-controller*"
    output.logstash:
      hosts: ["logstash-logstash.logging.svc.cluster.local:5044"]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: filebeat
    meta.helm.sh/release-namespace: logging
  creationTimestamp: "2022-03-11T19:00:32Z"
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/managed-by: Helm
    chart: filebeat-7.17.1
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat-daemonset-config
  namespace: logging
  resourceVersion: "187830"
  uid: 3fe171bb-650d-4c64-b85c-aad30756e37f
