apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - github.com/argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac
  - github.com/argoproj/argo-workflows/manifests/cluster-install/workflow-controller-rbac

namespace: argo
