apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogs-app
  namespace: argocd
spec:
  destination:
    namespace: gogs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gogs
    repoURL: https://github.com/vicen404/gitops-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
