apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-example
  namespace: nginx-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - nginx-10-1-1-120.traefik.me
    secretName: nginx-nginx-tls
  rules:
  - host: nginx-10-1-1-120.traefik.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serviceweb
            port:
              number: 80
