apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - ingress.yaml
  - nginx-tls.yaml

namespace: nginx-ns
