---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-basic-csi-nas1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 
  storageClassName: local-path
---
