---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-basic-csi-nas1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: basic-csi-nas1
---
