apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: px-mongodb-presnap-rule
  namespace: warp-prod
rules:
  - podSelector:
      app: warp-mongodb
    actions:
    - type: command
      value: mongo --eval "printjson(db.fsyncLock())"
