apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  annotations:
    stork.rule/pre-snapshot: px-mongodb-presnap-rule
    stork.rule/post-snapshot: px-mongodb-postsnap-rule
  name: snap-demo-warp-db-claim
  namespace: warp-prod
spec:
  persistentVolumeClaimName: demo-warp-db-claim
