apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-openai-server
spec:
  ingressClassName: nginx
  rules:
  - host: openai-server.10.1.1.130.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openai-server
            port:
              number: 5000
