---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ha
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
