apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-warp-db-claim
  namespace: warp-stage
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: demo-warp-db-claim-1
    stork.libopenstorage.org/snapshot-source-namespace: warp-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 2Gi
