apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: demo-warp-db-claim-1
  namespace: warp-prod
  annotations:
    stork.libopenstorage.org/snapshot-restore-namespaces: "warp-stage"
spec:
  persistentVolumeClaimName: demo-warp-db-claim
