apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - github/argoproj/argo-workflows/manifests/namespace-install/argo-server-rbac
  - github/argoproj/argo-workflows/manifests/namespace-install/workflow-controller-rbac

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: workflow-controller
    path: ./overlays/workflow-controller-deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: argo-server
    path: ./overlays/argo-server-deployment.yaml
namespace: argo-workflow
