apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-minio
  namespace: backuprepo
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - minio-10-1-1-120.traefik.me
    secretName: nginx-tls
  rules:
  - host: minio-10-1-1-120.traefik.me
    http:
      paths:
      - path: /
        backend:
          serviceName: minio
          servicePort: 443

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-console
  namespace: backuprepo
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - minio-tenant-10-1-1-120.traefik.me
    secretName: nginx-console-tls
  rules:
  - host: minio-tenant-10-1-1-120.traefik.me
    http:
      paths:
      - path: /
        backend:
          serviceName: repos3-console
          servicePort: 9443

