apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-console
  namespace: minio-operator
spec:
  rules:
  - host: minio-console-10-1-1-120.traefik.me
    http:
      paths:
      - path: /
        backend:
          serviceName: console
          servicePort: 9090
