apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: strimzi/strimzi-kafka-operator
    repoURL: https://strimzi.io/charts
    helm:
      releaseName: kafka-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
