apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim
  namespace: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: kadalu.storage-pool-1
