apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim
  namespace: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: portworx-rwx-gp1-sc
