apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim
  namespace: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: portworx-sc1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
