apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          class: nginx
          bootstrap:
            host: bootstrap-10-1-1-160.nip.io
          brokers:
          - broker: 0
            host: broker-0-10-1-1-160.nip.io
          - broker: 1
            host: broker-1-10-1-1-160.nip.io
          - broker: 2
            host: broker-2-10-1-1-160.nip.io
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
