---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-csi-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: kadalu.storage-pool-1
---
