apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minio-console
  namespace: minio-storage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  defaultBackend:
    service:
      name: minio
      port:
        number: 80
  tls:
  - hosts:
      - minio-storage-console.cluster.local
    secretName: nginx-storage-console
  - hosts:
      - minio-storage.cluster.local
    secretName: nginx-storage
  rules:
  - host: minio-storage-console.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-storage-console
            port:
              number: 9090
  - host: minio-storage.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 80
