apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
  namespace: warp-prod
  annotations:
    portworx/snapshot-type: cloud
spec:
  persistentVolumeClaimName: demo-warp-db-claim
